/// <reference types="../CTAutocomplete" />
/// <reference lib="es2015" />

import { skillsCommand } from "./commands/SkillsCommand"
import { dontRp } from "./commands/DontRP"
import { memberCommand } from "./commands/MemberCommand"
import { repartyCommand } from "./commands/RepartyCommand"
import { pingCommand } from "./commands/PingCommand"
import { bloomCommand } from "./commands/BloomCommand"
import { slayerCommand } from "./commands/SlayerCommand"
import { kuudraCommand } from "./commands/KuudraCommand"
import { pbCommand } from "./commands/PBCommand"
import "./commands/MiscCommands"
import "./commands/EnderPearlCommand"
import "./commands/SuperBoomCommand"
import "./commands/wikiCommand"
import "./commands/DsCommand"

import "./utils/FirstInstall"

import "./features/AutoArchitectDraft"
import "./features/AutoDSParty"
import "./features/AutoKicker"
import "./features/AutoReparty"
import "./features/AutoRequeue"
import "./features/AutoTransfer"
import "./features/BetterPartyFinderJoin"
import "./features/BlazeSolver"
import "./features/BlessingMessageHider"
import "./features/BlockUselessMessages"
import "./features/CakeNumbers"
import "./features/CellsAlignTimer"
import "./features/ChatEditor"
import "./features/CommandAliases"
import "./features/ContainerValue"
import "./features/CrystalHollowsMap"
import "./features/CrystalTimer"
import "./features/CustomEndInfo"
import "./features/DungeonCooldownTimer"
import "./features/dungeonChestProfit/DungeonChestProfit"
import "./features/EtherwarpOverlay"
import "./features/GyroRadius"
import "./features/HideGrayNumbers"
import "./features/HideLightning"
import "./features/HideNamesWith0Health"
import "./features/HideFallingBlocks"
import "./features/HideSoulweaverSkulls"
import "./features/HideThirdPersonCrosshair"
import "./features/ItemPriceLore"
import "./features/ItemValueOverlay"
import "./features/LividSolver"
import "./features/NoDeathAnimation"
import "./features/P3ArrowAlignSolver"
import "./features/PartyOverlay"
import "./features/PlayerLogs"
import "./features/RejoinReparty"
import "./features/RngMeter"
import "./features/RunOverview"
import "./features/RunSplits"
import "./features/ShowSecretClicks"
import "./features/SimonSaysSolver"
import "./features/SpeedDisplay"
import "./features/SpiritLeapNames"
import "./features/StacksTracker"
import "./features/TeleportMazeSolver"
import "./features/TermimalTracker"
import "./features/TerminalSolvers"
import "./features/TerminalSplits"
import "./features/TerminalTimer"
import "./features/ThreeWeirdosSolver"
import "./features/ToggleSprint"
import "./features/TriviaSolver"
import "./features/WaterBoardTimer"
import "./features/WatcherClear"